version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    expose:
      - "5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data/
    env_file: .env
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: app
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings
    command: bash entrypoint.sh
    volumes:
      - .:/app
    env_file: .env
    depends_on:
      postgres:
        condition: service_healthy
    restart: always
