# Generated by Django 5.0.6 on 2024-05-09 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='reviews_list',
            field=models.ManyToManyField(blank=True, null=True, to='book.review', verbose_name='Список отзывов'),
        ),
    ]
