# Generated by Django 5.0.6 on 2024-05-09 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_rename_author_review_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='Дата публикации'),
        ),
    ]
